name: Scrape VegaMovies (Playwright)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run scraper
        env:
          GPLINK_API: ${{ secrets.GPLINK_API }}
        run: python scrape.py

      - name: Commit and push data.json
        run: |
          git config user.name "FlixOcean Bot"
          git config user.email "bot@flixocean.com"
          git add data.json || true
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update data.json"
          git push || echo "Push skipped (no changes or permission issue)"
